import React from 'react';
import { FaExclamationTriangle } from 'react-icons/fa';

const AnalysisDisclaimer = () => {
  return (
    <div style={styles.container}>
      <div style={styles.iconBox}>
        <FaExclamationTriangle size={24} />
      </div>
      <div style={styles.content}>
        <h4 style={styles.title}>AI Accuracy & Liability Disclaimer</h4>
        <p style={styles.text}>
          This report is generated by an Artificial Intelligence model based on satellite imagery and general estimations. 
          While Solix strives for high accuracy, the results (including roof area, panel count, and financial savings) 
          are <strong>approximations only</strong>.
        </p>
        <p style={styles.text}>
          Actual solar generation can be affected by physical shading (trees/buildings), roof structure, and specific inverter efficiency. 
          <strong>Please consult a certified LECO/CEB engineer</strong> for a physical site inspection before making any financial investment.
        </p>
      </div>
    </div>
  );
};

const styles = {
  container: {
    marginTop: '30px',
    padding: '20px',
    backgroundColor: '#fffbeb', // Light yellow background (Warning style)
    border: '1px solid #fcd34d', // Yellow border
    borderRadius: '12px',
    display: 'flex',
    gap: '15px',
    alignItems: 'flex-start',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)'
  },
  iconBox: {
    color: '#d97706', // Dark Orange/Yellow
    marginTop: '2px'
  },
  content: {
    flex: 1
  },
  title: {
    margin: '0 0 8px 0',
    color: '#92400e', // Dark Brown text
    fontSize: '1rem',
    fontWeight: '700'
  },
  text: {
    margin: '0 0 8px 0',
    color: '#92400e',
    fontSize: '0.85rem',
    lineHeight: '1.5'
  }
};

export default AnalysisDisclaimer;