import React from 'react';
import './ReportExportSection.css';
import { FaFileInvoice, FaDownload } from 'react-icons/fa'; // Using react-icons for document and download icons

const ReportExportSection = ({ isAnalysisComplete = false, onExportReport }) => {
  const buttonClassName = isAnalysisComplete ? 'export-button' : 'export-button disabled';

  return (
    
    <div className="report-export-section glass-card">
      <div className="header-area">
        <FaFileInvoice className="header-icon" />
        <h2 className="title">SOLIX Analysis Report</h2>
        <p className="subtitle">A comprehensive, AI-generated feasibility and insight summary</p>
      </div>

      <div className="report-content-preview">
        <ul>
          <li>Rooftop detection & usable area estimation (computer vision)</li>
          <li>Recommended PV system size (kW)</li>
          <li>Estimated annual energy production (kWh)</li>
          <li>Monthly savings & payback period</li>
          <li>Location-based solar & climate data</li>
          <li>AI decision explanation & assumptions</li>
        </ul>
      </div>

      <button
        className={buttonClassName}
        onClick={isAnalysisComplete ? onExportReport : null}
        disabled={!isAnalysisComplete}
        title={!isAnalysisComplete ? "Run analysis to enable report export" : ""}
      >
        Export Full Analysis Report <FaDownload className="download-icon" />
      </button>

      <p className="microcopy">
        Includes rooftop analysis, PV sizing, energy estimates, savings & payback.
        <br />
        PDF format. Auto-generated by SOLIX AI.
      </p>
    </div>
  );
};

export default ReportExportSection;